### ISSUE TITLE
Current problem: had to switch to pip and resource_path not being set

### ISSUE THREAD

**Issue by OzarkShepherd** [gramps-project/flatpak#22]
Since setup.py is deprecated in the current Gnome Platform, I had to switch to pip for installing python apps in the manifest.  The problem with using pip is that the resource path is no longer getting set correctly.  So even though 5.1.5 flatpak compiles now, the flatpak does not open Gramps and gives an error about unable to determine resource path.  

So I looked at https://gramps-project.org/wiki/index.php/Gramps_5.1_Wiki_Manual_-_Command_Line#GRAMPS_RESOURCES and https://gramps.discourse.group/t/2-questions-that-involve-linux/634 to learn how to set the resource path.  There are a couple problems, the flatpak command is different so I don't know how to set the resource path in the desktop file while launching the app; and the other problem is that the path is different in flatpaks.  I've been trying variations of /app/lib/ and /app/bin/ in config-settings and build-options for the resource path, and /app/lib/python3.9/site-packages/gramps for the python path.  It compiles on both github and my pc, although it throws a "no <component> node" error at the end when I build on home pc, which I haven't figured out yet.  The manifest is at the url below, and I didn't submit it here yet because it doesn't run.
https://github.com/OzarkShepherd/flatpak/blob/main/org.gramps_project.Gramps.yml

I'll probably post this issue at a flathub discourse to see if anyone there can see a manifest error in the config-options.

**Comment by Nick-Hall** [comment]
Try:

`GRAMPS_RESOURCES=/app/share/gramps`

**Comment by OzarkShepherd** [comment]
Thank you, does python path look right?
`PYTHONPATH=/app/lib/python3.9/site-packages/gramps`

**Comment by Nick-Hall** [comment]
Yes, the `PYTHONPATH` looks right.

**Comment by Nick-Hall** [comment]
You should be able to install from pip in the next major release (v5.2).  See gramps PR [#1106](https://github.com/gramps-project/gramps/pull/1106)
