### ISSUE TITLE
Add Wayland support

### ISSUE THREAD

**Issue by a-andre** [gramps-project/flatpak#7]
Replace finish arg `  - --socket=x11` by
```
  - --socket=fallback-x11
  - --socket=wayland
```

See https://github.com/flathub/flathub/issues/1452.

**Comment by OzarkShepherd** [comment]
I couldn't get the flatpak to work with wayland while troubleshooting, and having both slows the launch down when wayland fails and gramps fallsback to x11, so somebody at reddit mentioned why have both for a sandbox app?  It could be added back in though.

**Comment by OzarkShepherd** [comment]
It's added back in with the other changes in the pull request.
